repos:
  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: bdba95f94147c2f5da7eda81e15cdd92c41758ba
    hooks:
      - id: go-vet
      - id: go-static-check # install https://staticcheck.io/docs/
      - id: golangci-lint # requires github.com/golangci/golangci-lint
  - repo: local
    hooks:
      - id: go-errcheck
        name: go-errcheck
        entry: errcheck -exclude .errcheck_excludes.txt ./...
        language: system
        pass_filenames: false
      - id: make-fmt # requires 'go install mvdan.cc/gofumpt@latest' and 'go install github.com/daixiang0/gci@latest'
        name: make-fmt
        entry: make fmt
        language: system
        pass_filenames: false
